### ISSUE TITLE
Error: Cannot add a Characteristic with the same UUID. 

### ISSUE THREAD

**Issue by shidevil** [lucavb/homebridge-hc-sr501#10]
Hi,

I restarted my HomeKit and tried to set up homebridge again. Getting this error. 

Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 00000023-0000-1000-8000-0026BB765xxx

What could the idea be to solve this?

**Comment by shidevil** [comment]
Attached is the log. I have tried changing the name of the sensor but it does not work.

`Jul 10 17:49:36 raspberrypi homebridge[1758]: [7/10/2020, 17:49:36] Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 00000023-0000-1000-8000-0026BB765291
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at AccessoryInformation.Service._this.addCharacteristic (/usr/lib/node_modules/hap-nodejs/dist/lib/Service.js:111:27)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at new AccessoryInformation (/usr/lib/node_modules/hap-nodejs/dist/lib/gen/HomeKit.js:3911:15)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at new HomebridgeSR501Sensor (/usr/lib/node_modules/homebridge-hc-sr501/dist/index.js:20:35)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at /usr/lib/node_modules/homebridge/lib/server.js:246:39
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at Array.forEach (<anonymous>:null:null)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:222:33)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at Server.start (/usr/lib/node_modules/homebridge/lib/server.js:76:18)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at cli (/usr/lib/node_modules/homebridge/lib/cli.js:88:12)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at Module.load (internal/modules/cjs/loader.js:986:32)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Jul 10 17:49:36 raspberrypi homebridge[1758]:     at internal/main/run_main_module.js:17:47`

**Comment by lucavb** [comment]
Can you please share your config for homebridge with me. Make sure to remove sensitive information before posting it here.

**Comment by shidevil** [comment]
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:34",
    "port": 51826,
    "pin": "031-45-155"
  },

  "accessories": [
    {
      "accessory": "TwineTemperature",
      "name": "Temperature",
      "url": "xxxxxxxxx",
      "http_method": "GET",
      "refresh": 600
    }
  ],

  "platforms": [{
  "platform": "TplinkSmarthome",
  "name": "TplinkSmarthome"
},
    {
      "platform": "BroadlinkRM",
      "name": "Broadlink RM",
      "hideWelcomeMessage": true,
      "hideScanFrequencyButton": true,
      "hideLearnButton": true,
      "accessories": [{
          "name": "Bedroom On/Off",
          "host": "xx",
          "type": "switch",
          "data": {
            "on": "xxx",
            "off": "xxx"
          }
        },
        {
          "name": "Bedroom On/Off",
          "host": "192.168.1.189",
          "type": "switch",
          "data": {
            "on": "xxx",
            "off": "xxx"
          }
        },
        {
          "name": "Air Conditioner",
          "type": "air-conditioner",
          "host": "xxx",
          "defaultCoolTemperature": 25,
          "ignoreTemperatureWhenOff": true,
          "minTemperature": 10,
          "maxTemperature": 35,
          "data": {
            "off": "xxx",
            "temperature25": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature16": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature17": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature18": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature19": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature20": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature21": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature22": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature23": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature24": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature26": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature27": {
              "pseudo-mode": "cool",
              "data": "xxx"
            }
          }
        },
        {
          "name": "Air Conditioner",
          "type": "air-conditioner",
          "host": "xx",
          "pseudoDeviceTemperature": 28,
          "ignoreTemperatureWhenOff": true,
          "defaultCoolTemperature": 25,
          "minTemperature": 10,
          "maxTemperature": 35,
          "data": {
            "off": "xxx",
            "temperature25": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature16": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature17": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature18": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature19": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature20": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature21": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature22": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature23": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature24": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature26": {
              "pseudo-mode": "cool",
              "data": "xxx"
            },
            "temperature27": {
              "pseudo-mode": "cool",
              "data": "xxx"
            }
          }
        }
      ]
    },
    {
  "platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "Camera",
      "manufacturer": "xxx",
      "model": "xxx",
      "serialNumber": "xxx",
      "firmwareRevision": "1.0.0",
      "videoConfig": {
        "source": "xxx",
        "stillImageSource": "xxx",
        "maxStreams": 2,
        "maxWidth": 1280,
        "maxHeight": 720,
        "maxFPS": 24,
        "maxBitrate":128,
        "videoFilter":"none",
        "vcodec": "copy",
        "audio":false
      }
    },
    {
      "name": "Door Camera",
      "manufacturer": "xxx",
      "model": "xxx",
      "serialNumber": "xxx",
      "firmwareRevision": "xxx",
      "videoConfig": {
        "source": "xxx",
        "stillImageSource": "xxx",
        "maxStreams": 2,
        "maxWidth": 2560,
        "maxHeight": 1440,
        "maxBitrate": 4000,
        "maxFPS": 30,
        "videoFilter":"none",
        "vcodec": "copy",
        "audio":false
      }
    }
  ]
}
  ]
}
```

**Comment by lucavb** [comment]
Does one of your platforms create another accessory that is named `Motion`. It seems that the posted uuid belongs to the name characteristic so an error there points to that conclusion. 

https://developers.homebridge.io/#/characteristic/Name

**Comment by shidevil** [comment]
Yes, i actually saw that it is characteristic name. But nope, none of my platform create another accessory name motion. It's a small issue to me, as i have moved my homebridge to dockers already and i will use my raspberry pi as my sensor hub for this and other sensors.

**Comment by lucavb** [comment]
Hey, sorry this got kind of lost, but the other issue I just fixed might be related to your problem. Would you have another look at version 1.0.6?
