### ISSUE TITLE
Error appeared and Homebridge stopped.

### ISSUE THREAD

**Issue by piroshi1112** [lucavb/homebridge-hc-sr501#8]
The other day I installed the plugin and wrote it in config.json as described in the manual, but the following error appeared and Homebridge stopped. Is there any workaround?

```
Mar 31 00:59:01 socrates homebridge[599]: [3/31/2020, 12:59:01 AM] Error: The requested accessory 'HC-SR501' was not registered by any plugin.
Mar 31 00:59:01 socrates homebridge[599]:     at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
Mar 31 00:59:01 socrates homebridge[599]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
Mar 31 00:59:01 socrates homebridge[599]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
Mar 31 00:59:01 socrates homebridge[599]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Mar 31 00:59:01 socrates homebridge[599]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mar 31 00:59:01 socrates homebridge[599]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Mar 31 00:59:01 socrates homebridge[599]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Mar 31 00:59:01 socrates homebridge[599]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Mar 31 00:59:01 socrates homebridge[599]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Mar 31 00:59:01 socrates homebridge[599]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Mar 31 00:59:01 socrates homebridge[599]:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
Mar 31 00:59:01 socrates homebridge[599]:     at startup (internal/bootstrap/node.js:283:19)
Mar 31 00:59:01 socrates homebridge[599]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Mar 31 00:59:01 socrates homebridge[599]: [3/31/2020, 12:59:01 AM] Got SIGTERM, shutting down Homebridge...
```

**Comment by lucavb** [comment]
Such a small plugin and still missed the error. Version 1.0.3 is out on npmjs. Thank you for posting this bug!
